[phases.setup]
nixPkgs = ["go"]

[phases.build]
cmds = [
    "go mod download",
    "go build -ldflags='-w -s' -o main ."
]

[start]
cmd = "./main"

[variables]
CGO_ENABLED = "0"
GO111MODULE = "on"
PORT = "8080"
