[build]
builder = "NIXPACKS"

[deploy]
startCommand = "./main"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
sleepApplication = false

[environment]
PORT = "8080"
CGO_ENABLED = "0"
