[build]
builder = "NIXPACKS"

[deploy]
startCommand = "./main"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
sleepApplication = false
healthcheckInterval = 30

[environment]
PORT = "8080"
CGO_ENABLED = "0"
GO111MODULE = "on"
